[tool.poetry]
name = "django-hstore-widget"
version = "0.0.9"
description = "Human friendly HStoreWidget. Continual of django-admin-hstore-widget."
authors = [
    "Alexandre Dufour <adufour@poka.io>",
    "baseplate-admin <61817579+baseplate-admin@users.noreply.github.com>"
]
readme = "README.md"
license = "MIT"
packages = [{include = "django_hstore_widget"}]
classifiers = [ 
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 2.1",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/baseplate-admin/django-hstore-widget/issues"
"homepage" = "https://github.com/baseplate-admin/django-hstore-widget"
"repository" = "https://github.com/baseplate-admin/django-hstore-widget"

[tool.poetry.dependencies]
python = ">=3.8"
django = "*"


[tool.poetry.group.test.dependencies]
pytest = "^8.0.1"
pytest-django = "^4.8.0"
psycopg2 = {extras = ["binary"], version = "^2.9.10"}
psycopg = {extras = ["binary"], version = "^3.2.3"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
