/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DjangoHstoreWidget {
        /**
          * @default undefined
         */
        "add_svg_src": string | undefined;
        /**
          * @default 40
         */
        "cols": number;
        /**
          * @default undefined
         */
        "delete_svg_src": string | undefined;
        /**
          * @default undefined
         */
        "edit_svg_src": string | undefined;
        "field_name": string;
        "json": string;
        /**
          * @default 10
         */
        "rows": number;
    }
}
declare global {
    interface HTMLDjangoHstoreWidgetElement extends Components.DjangoHstoreWidget, HTMLStencilElement {
    }
    var HTMLDjangoHstoreWidgetElement: {
        prototype: HTMLDjangoHstoreWidgetElement;
        new (): HTMLDjangoHstoreWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "django-hstore-widget": HTMLDjangoHstoreWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DjangoHstoreWidget {
        /**
          * @default undefined
         */
        "add_svg_src"?: string | undefined;
        /**
          * @default 40
         */
        "cols"?: number;
        /**
          * @default undefined
         */
        "delete_svg_src"?: string | undefined;
        /**
          * @default undefined
         */
        "edit_svg_src"?: string | undefined;
        "field_name": string;
        "json": string;
        /**
          * @default 10
         */
        "rows"?: number;
    }
    interface IntrinsicElements {
        "django-hstore-widget": DjangoHstoreWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "django-hstore-widget": LocalJSX.DjangoHstoreWidget & JSXBase.HTMLAttributes<HTMLDjangoHstoreWidgetElement>;
        }
    }
}
