/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DjangoHstoreWidget {
        "add_svg_src": string;
        "delete_svg_src": string;
        "field_name": string;
        "json": string;
    }
}
declare global {
    interface HTMLDjangoHstoreWidgetElement extends Components.DjangoHstoreWidget, HTMLStencilElement {
    }
    var HTMLDjangoHstoreWidgetElement: {
        prototype: HTMLDjangoHstoreWidgetElement;
        new (): HTMLDjangoHstoreWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "django-hstore-widget": HTMLDjangoHstoreWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DjangoHstoreWidget {
        "add_svg_src"?: string;
        "delete_svg_src"?: string;
        "field_name"?: string;
        "json"?: string;
    }
    interface IntrinsicElements {
        "django-hstore-widget": DjangoHstoreWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "django-hstore-widget": LocalJSX.DjangoHstoreWidget & JSXBase.HTMLAttributes<HTMLDjangoHstoreWidgetElement>;
        }
    }
}
