name: CI

on: [push]

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Node.JS
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm ci

            - name: Build ( frontend )
              run: npm run build

    release:
        name: Release
        if: "startsWith(github.ref, 'refs/tags/')"
        runs-on: ubuntu-latest
        needs: [test]

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build ( frontend )
              run: npm run build

            - uses: actions/checkout@v4
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            # - name: Install python dependencies
            #   run: |
            #       poetry install --sync --no-interaction --no-root

            - name: Set pypi token
              run: |
                  poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

            - name: Publish
              run: |
                  poetry publish --build
